server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:instructions}
    username: ${DB_USERNAME:instructions}
    password: ${DB_PASSWORD:instructions}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    baseline-on-migrate: true
    clean-disabled: false
    validate-on-migrate: false
    locations: classpath:db/migration
logging:
  level:
    root: INFO

app:
  admin:
    username: ${APP_ADMIN_USERNAME:admin}
    password: ${APP_ADMIN_PASSWORD:}
  jwt:
    secret: ${APP_JWT_SECRET:change-me-please-change-me-please}
    issuer: ${APP_JWT_ISSUER:instructions-api}
    access-token-ttl: ${APP_JWT_ACCESS_TOKEN_TTL:PT1H}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
