spring:
  application:
    name: instructions-backend
  datasource:
    url: jdbc:postgresql://${INSTRUCTIONS_DB_HOST:postgres}:${INSTRUCTIONS_DB_PORT:5432}/${INSTRUCTIONS_DB_NAME:instructions}
    username: ${INSTRUCTIONS_DB_USER:instructions}
    password: ${INSTRUCTIONS_DB_PASSWORD:instructions}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    root: INFO
    com.boldin.instructions: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus
  metrics:
    tags:
      application: instructions-backend
