apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-index
  namespace: apps
data:
  index.html: |
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Frontend placeholder</title>
        <style>
          body { font-family: sans-serif; padding: 2rem; text-align: center; }
          h1 { color: #2563eb; }
        </style>
      </head>
      <body>
        <h1>It works!</h1>
        <p>The placeholder frontend is up and running.</p>
      </body>
    </html>
