# k8s/kafka-topics.yaml   (Strimzi CRDs)
apiVersion: kafka.strimzi.io/v1beta2          # KafkaTopic CRD: https://strimzi.io/docs/operators/latest/deploying.html#type-KafkaTopic-reference
kind: KafkaTopic
metadata:
  name: sms-auth-send
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster            # К какому Kafka-кластеру относится: https://strimzi.io/docs/operators/latest/deploying.html#ref-kafka-topic-str
spec:
  topicName: test.sputnik.fct.sms.auth.send.0 # Реальное имя топика в Kafka
  partitions: 3                                # Параллелизм/пропускная способность
  replicas: 3                                  # Фактор репликации (не меньше числа брокеров)
  config:                                      # Настройки топика: https://kafka.apache.org/documentation/#topicconfigs
    retention.ms: 604800000                    # 7 дней хранения
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sms-3ds-send
  namespace: kafka
  labels: { strimzi.io/cluster: my-cluster }
spec:
  topicName: test.sputnik.fct.sms.3ds.send.0
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sms-non-auth-send
  namespace: kafka
  labels: { strimzi.io/cluster: my-cluster }
spec:
  topicName: test.sputnik.fct.sms.non_auth.send.0
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sms-vip-send
  namespace: kafka
  labels: { strimzi.io/cluster: my-cluster }
spec:
  topicName: test.sputnik.fct.sms.vip.send.0
  partitions: 3
  replicas: 3
