# k8s/pdb.yaml
apiVersion: policy/v1                         # PDB: https://k8s.io/docs/concepts/workloads/pods/disruptions/
kind: PodDisruptionBudget
metadata:
  name: my-service
  namespace: apps
spec:
  minAvailable: 1                             # Минимум 1 под должен остаться при drain/эвакуации
  selector:
    matchLabels:
      app: my-service
