apiVersion: v1
kind: Secret
metadata:
  name: my-service-secrets
  namespace: apps
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres.apps.svc.cluster.local:5432/app"
  DB_USER: "appuser"
  DB_PASSWORD: "changeme"
