spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: instructions-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/instructions
    username: instr_user
    password: instr_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: false
    open-in-view: false

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.boldin.instructions: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      probes:
        enabled: true

