spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: instructions-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/instructions
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.boldin.instructions: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      probes:
        enabled: true
