apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-ingress.yaml
images:
  - name: frontend
    newName: ghcr.io/boldrqwe/frontend
    newTag: latest
