name: Backend CI/CD

on:
  push:
    branches:
      - main
      - work
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/instructions-backend

jobs:
  build:
    name: Test backend and publish container image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.image-tag.outputs.value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем стабильный Temurin JDK 21 и подключаем кэш Maven.
      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Показываем версии инструментов, чтобы диагностика была прозрачной.
      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -version

      # Гоним юнит-тесты и проверяем, что код собирается на чистом агенте.
      - name: Run Maven verify
        working-directory: backend
        run: mvn -B -Dspring.profiles.active=test verify

      # Если тесты упали, отчёты будут приложены к джобе.
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-surefire-reports
          path: backend/target/surefire-reports
          if-no-files-found: ignore

      # Авторизация в GitHub Container Registry нужна только когда пушим в main.
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Настраиваем отдельного билдера, чтобы работали BuildKit и GHA-кэш.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Собираем Docker-образ. На PR просто проверяем, что сборка проходит, а на main ещё и пушим.
      - name: Build backend image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Передаём тег образа в следующую джобу, чтобы не вычислять его повторно.
      - name: Expose image tag for deploy job
        id: image-tag
        run: echo "value=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

  deploy:
    name: Cluster smoke (namespace only)
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.2'

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p "$HOME/.kube"
          echo "$KUBE_CONFIG_B64" | base64 --decode > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

      - name: Cluster info
        run: |
          set -e
          kubectl cluster-info
          kubectl version --short
          kubectl auth can-i '*' '*' || true
          kubectl get nodes -o wide

      - name: Ensure namespace exists
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl get ns apps

      - name: Recent events
        run: |
          kubectl get events --sort-by=.lastTimestamp | tail -n 20 || true
