name: k8s-smoke

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Configure kubectl from secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Who am I
        run: kubectl auth whoami

      - name: Can I in prod-app?
        run: |
          kubectl -n prod-app auth can-i get pods
          kubectl -n prod-app get cm gha-smoke -o yaml || echo "gha-smoke not found (ok)"
