name: PR → pr-latest (backend)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

concurrency:
  group: pr-latest-backend
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/boldrqwe/instructions_backend

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:pr-latest
            ${{ env.IMAGE }}:pr-${{ github.event.number }}-${{ github.sha }}

