name: PR → pr-latest (backend)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

concurrency:
  group: pr-latest-backend
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/boldrqwe/instructions_backend

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          no-cache: true                   # 🚀 ключевая строка — отключает Docker кэш
          pull: true                       # ⚙️ всегда тянет свежие базовые образы
          tags: |
            ${{ env.IMAGE }}:pr-latest
            ${{ env.IMAGE }}:pr-${{ github.event.number }}-${{ github.sha }}

      - name: Display pushed images
        run: |
          echo "✅ Successfully pushed:"
          echo " - ${{ env.IMAGE }}:pr-latest"
          echo " - ${{ env.IMAGE }}:pr-${{ github.event.number }}-${{ github.sha }}"
